import { app, BrowserWindow, protocol, net } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { pathToFileURL } from 'url';
import { setupIpcHandlers } from './ipcHandlers';
import { autoUpdater } from 'electron-updater';
import { loadSettingsFromDisk } from './ipcHandlers/settingsHandlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

// Ensure single instance to handle file open events
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
}

app.on('second-instance', (_event, argv) => {
  if (!mainWindow) return
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.focus();
  mainWindow.webContents.send('open-file', argv[1]);
});

// macOS open-file handler
app.on('open-file', (event, filePath) => {
  event.preventDefault();
  if (mainWindow) {
    mainWindow.webContents.send('open-file', filePath);
  }
});

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 720,
    width: 1280,
    minWidth: 640,
    minHeight: 480,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: false,
    },
    backgroundColor: '#121212',
    show: false,
    frame: false, // Make window borderless
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: 'rgba(0, 0, 0, 0)',
      symbolColor: '#ffffff',
      height: 30,
    },
    // dark theme
    darkTheme: true,
  });



  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Set CSP to allow our custom protocol and development tools
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: local-file: file: ws: wss:; " +
          "media-src 'self' data: local-file: file: blob: https://filesamples.com; " +
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' ws: wss:; " +
          "connect-src 'self' ws: wss:;"
        ]
      }
    });
  });



  // Show window when ready to avoid flickering
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  // Open the DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }

  // Set up IPC handlers for file operations
  initializeIpcHandlers();
};

// Set up IPC handlers for communication between renderer and main process
const initializeIpcHandlers = () => {
  setupIpcHandlers(mainWindow!);
};



// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // Handle custom protocol for local files
  protocol.handle('local-file', (req) => {
    let filePath = req.url.replace('local-file://', '');
    if (process.platform !== 'win32' && !filePath.startsWith('/')) filePath = `/${filePath}`;

    // Check if file exists
    if (fs.existsSync(filePath)) {
      return net.fetch(pathToFileURL(filePath).toString());
    } else {
      return new Response('File not found', {
        status: 404,
        headers: { 'content-type': 'text/plain' }
      });
    }
  });

  createWindow();

  // Auto-update: check based on user setting
  try {
    // Configure GitHub provider explicitly and allow prereleases (for -dev tags)
    autoUpdater.allowPrerelease = true;
    autoUpdater.setFeedURL({ provider: 'github', owner: 'zardoy', repo: 'aqua-player' });
    const settings = loadSettingsFromDisk();
    const autoUpdateEnabled = !!settings['updates.autoUpdate'];
    if (autoUpdateEnabled) {
      autoUpdater.autoDownload = true;
      autoUpdater.on('update-available', () => {
        mainWindow?.webContents.send('update-available');
      });
      autoUpdater.on('update-downloaded', () => {
        mainWindow?.webContents.send('update-downloaded');
      });
      autoUpdater.checkForUpdatesAndNotify();
    }
  } catch {}
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
